# define a decorator to import the docstring from a function to another function
from typing import Callable

def sowraps(func: Callable) -> Callable:
    def decorator(wrapper: Callable) -> Callable:
        doc = func.__doc__
        # parse the docstring to remove Example section
        if doc is not None:
            doc = doc.split("Examples")[0]
            doc = doc.strip()

        doc += f"""
        
        Notes
        -----
        The docstring of this function is autogenerated from :meth:`seaborn.objects.{func.__qualname__}`.
        """
        wrapper.__doc__ = doc
        return wrapper
    return decorator
